---
title: "Wykresy - volcanoplots"
author: "Aleksandra Dąbrowska, Alicja Gosiewska"
date: "17 May 2017"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

Weźmy pierwsze 500 genów o najbardziej zróżnicowanej ekspresji i metylacji.
```{r,echo=FALSE}
library(MetExpR)
library(plyr)

ekspresja_500 <-test_expr_brca[order(test_expr_brca$pval, decreasing= F),]
ekspresja_500 <- ekspresja_500[c(1:500),]


metylacja_500 <-test_met_brca[order(test_met_brca$pval, decreasing= F),]
metylacja_500 <- metylacja_500[c(1:500),]

x <- ekspresja_500[which(ekspresja_500$id %in% metylacja_500$id),]

genes <- x$id


```

W obu zbiorach danych powtarza się 19 genów.

# Volcanoploty

```{r,echo=FALSE,warning=FALSE, message=FALSE}

#genes <- c("BRCA1","BRCA2")

condition.m <-ifelse(BRCA_methylation_all$SUBTYPE=="LumA","LumA","other")
condition.e <-ifelse(BRCA_mRNAseq_all$SUBTYPE=="LumA","LumA","other")

volcano_plot(test_expr_brca, ngen=genes)
volcano_plot(test_met_brca, ngen=genes)
```

# Dane dla genów z volcanoplotów

```{r,echo=FALSE, message=FALSE, fig.width=19, fig.height=5}
genes<- sort(genes)
plot <- list()
for (i in 1:length(genes)){
  #plot[[i]] <- genereg_vs_met(BRCA_methylation_all[,-1], condition.m, gene="BRCA2")

   plot[[i]] <- visual_volc(condition.e, condition.m, BRCA_methylation_all[,-1],BRCA_mRNAseq_all[,-1], genes[i])

  
  }


```

# Wizytówki dla metylacji

```{r,echo=FALSE,warning=FALSE, message=FALSE}

plot <- list()
for (i in 1:length(genes)){
  #plot[[i]] <- genereg_vs_met(BRCA_methylation_all[,-1], condition.m, gene="BRCA2")

   plot[[i]] <- visual_gene(condition.e, condition.m, BRCA_methylation_all[,-1],BRCA_mRNAseq_all[,-1], gene=genes[i], test_expr_brca, test_met_brca)

  
  }


```
