---
title: "Wykresy - porównanie danych dla survival status"
author: "Aleksandra Dąbrowska, Alicja Gosiewska"
date: "24 May 2017"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(MetExpR)
dane_metylacja_17 <- chromosome_data(LUSC_methylation_all_surv,17)
dane_metylacja_17_gene <- map_to_gene(dane_metylacja_17)
names <- colnames(dane_metylacja_17_gene)
x<- colnames(dane_metylacja_17)[1:2]
names2 <- c(names,x)
dane_ekspresja_17 <- LUSC_mRNAseq_all_surv[,which(colnames(LUSC_mRNAseq_all_surv) %in% names2)]

condition.m <- ifelse(dane_metylacja_17$survival_status==1, "Dead","Alive")
condition.e <- ifelse(dane_ekspresja_17$survival_status==1, "Dead","Alive")
test_met_lusc <- test_diff(dane_metylacja_17_gene,condition.m,"ttest")
test_expr_lusc <- test_diff(dane_ekspresja_17[,-c(1,2)],condition.e,"nbinom2")
```

Weźmy pierwsze 200 genów o najbardziej zróżnicowanej ekspresji i metylacji.
```{r,echo=FALSE}
library(plyr)

ekspresja_100 <-test_expr_lusc[order(test_expr_lusc$pval, decreasing= F),]
ekspresja_100 <- ekspresja_100[c(1:100),]


metylacja_100 <-test_met_lusc[order(test_met_lusc$pval, decreasing= F),]
metylacja_100 <- metylacja_100[c(1:100),]

x <- ekspresja_100[which(ekspresja_100$id %in% metylacja_100$id),]

genes <- x$id


```


# Volcanoploty

```{r,echo=FALSE,warning=FALSE, message=FALSE}

volcano_plot(test_expr_lusc, ngen=genes)
volcano_plot(test_met_lusc, ngen=genes)
```

# Dane dla genów z volcanoplotów

```{r,echo=FALSE, message=FALSE, fig.width=19, fig.height=5}
genes<- sort(genes)
plot <- list()
for (i in 1:length(genes)){
  #plot[[i]] <- genereg_vs_met(BRCA_methylation_all[,-1], condition.m, gene="BRCA2")

   plot[[i]] <- visual_volc(condition.e, condition.m, dane_metylacja_17[,-c(1,2)],dane_ekspresja_17[,-c(1,2)], genes[i])

  
  }


```

# Wizytówki dla metylacji

```{r,echo=FALSE,warning=FALSE, message=FALSE}

plot <- list()
for (i in 1:length(genes)){
  #plot[[i]] <- genereg_vs_met(BRCA_methylation_all[,-1], condition.m, gene="BRCA2")

   plot[[i]] <- visual_gene(condition.e, condition.m, dane_metylacja_17[,-c(1,2)],dane_ekspresja_17[,-c(1,2)], gene=genes[i], test_expr_lusc, test_met_lusc)

  
  }


```
